name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Build
      run: g++ -std=c++17 -Wall -Wextra -o main 04_Compound_Types_Ref_And_Pointers/*.cpp
    - name: Run
      run: ./main
